using System.Text;
using System.Text.Json;
using GenerateDocService.Engine.Abstractions;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace GenerateDocService.Engine.QuestPdf;

[DocumentEngine(
    "questpdf",
    InputFormats = ["json"],
    OutputFormats = ["pdf"],
    TemplateFormats = ["json", "txt", "html", "md", "markdown"],
    Priority = 200)]
public sealed class QuestPdfDocumentGenerationEngine : IDocumentGenerationEngine
{
    static QuestPdfDocumentGenerationEngine()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public string Name => "questpdf";

    public bool CanHandle(string inputFormat, string outputFormat, string? templateFormat = null)
        => string.Equals(inputFormat, "json", StringComparison.OrdinalIgnoreCase)
           && string.Equals(outputFormat, "pdf", StringComparison.OrdinalIgnoreCase);

    public Task<IReportResult> GenerateAsync(IReportRequest request, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();

        if (!CanHandle(request.InputFormat, request.OutputFormat, request.TemplateFormat))
        {
            throw new InvalidOperationException($"Engine '{Name}' cannot handle {request.InputFormat} -> {request.OutputFormat}.");
        }

        var payloadText = Encoding.UTF8.GetString(request.Payload.Span);
        using var payload = JsonDocument.Parse(payloadText);
        var jsonText = JsonSerializer.Serialize(payload, new JsonSerializerOptions { WriteIndented = true });
        var title = payload.RootElement.ValueKind == JsonValueKind.Object
                    && payload.RootElement.TryGetProperty("title", out var titleProperty)
            ? titleProperty.GetString() ?? "Generated Document"
            : "Generated Document";

        var pdfBytes = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(40);
                    page.DefaultTextStyle(text => text.FontSize(12));

                    page.Header()
                        .Text(title)
                        .SemiBold()
                        .FontSize(20)
                        .FontColor(Colors.Blue.Medium);

                    page.Content()
                        .Column(column =>
                        {
                            column.Spacing(12);
                            column.Item().Text($"Engine: {Name}");
                            column.Item().Text($"Request: {request.RequestId}");
                            column.Item().Text("Payload").SemiBold();
                            column.Item().Padding(12).Background(Colors.Grey.Lighten3).Text(jsonText);
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(text =>
                        {
                            text.Span("Generated by GenerateDocService · Page ");
                            text.CurrentPageNumber();
                            text.Span(" / ");
                            text.TotalPages();
                        });
                });
            })
            .GeneratePdf();

        IReportResult result = new QuestPdfReportResult(
            request.RequestId,
            $"{request.RequestId}.pdf",
            pdfBytes,
            request.Metadata);

        return Task.FromResult(result);
    }

    private sealed class QuestPdfReportResult(
        string requestId,
        string fileName,
        byte[] content,
        IReadOnlyDictionary<string, string> metadata) : IReportResult, IDisposable
    {
        private readonly MemoryStream _content = new(content, writable: false);

        public string RequestId { get; } = requestId;
        public string FileName { get; } = fileName;
        public string ContentType { get; } = "application/pdf";
        public string OutputFormat { get; } = "pdf";
        public long ContentLength { get; } = content.LongLength;
        public Stream Content => _content;
        public string? Checksum => null;
        public IReadOnlyDictionary<string, string> Metadata { get; } = metadata;

        public void Dispose()
        {
            _content.Dispose();
        }
    }
}
